run_name: v003-02-24-23-1b-c4-0pt7
save_folder: &save_folder s3://mosaicml-internal-checkpoints-shared/matthew/hero-pretrain-data-exps/v003-02-24-23-1b-c4-0pt7/checkpoints
 
gpu_type: a100_40gb
gpu_num: 32
platform: r12z1
image: mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04

integrations:  
  - integration_type: wandb
    project: hero-pretrain-data-exps
    entity: mosaic-ml
  - integration_type: git_repo
    git_repo: mosaicml/examples
    # git_branch: hero-2-24
    git_commit: b798cd0118d16522278727b4b0e87132336873ea 
    pip_install: '.[llm]'

command: |
  cd examples/examples/llm
  composer main.py /mnt/config/parameters.yaml

parameters:
  data_local: /tmp/c4
  train_data_remote: s3://mosaicml-internal-checkpoints-shared/matthew/c4/keep_0pt9/
  eval_data_remote: s3://mosaicml-internal-checkpoints-shared/c4/gpt2-tokenized-2k/
  tokenizer_name: gpt2
  max_seq_len: 2048
  global_seed: 17

  # Run Name
  run_name: # If left blank, will be read from env var $COMPOSER_RUN_NAME

  # Model
  model:
    name: mosaic_gpt
    init_device: meta
    tokenizer_name: ${tokenizer_name}
    d_model: 2048
    n_heads: 16 # Modified 24->16 so that d_head == 128 to satisfy FlashAttention
    n_layers: 24
    mlp_ratio: 4
    max_seq_len: ${max_seq_len}
    vocab_size: 50304
    init_std: 0.02
    attn_pdrop: 0.0
    resid_pdrop: 0.0
    emb_pdrop: 0.0
    attn_impl: flash
    low_precision_layernorm: true
    attn_clip_qkv: 2.0
    bias: true

  # Tokenizer
  tokenizer:
    type: hftokenizer
    args:
      tokenizer_name: ${tokenizer_name}
      max_seq_len: ${max_seq_len}

  # Dataloaders
  train_loader:
    name: text
    dataset:
      local: ${data_local}
      remote: ${train_data_remote}
      split: train
      shuffle: true
      tokenizer_name: ${tokenizer_name}
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
    drop_last: true
    num_workers: 8

  eval_loader:
    name: text
    dataset:
      local: ${data_local}
      remote: ${eval_data_remote}
      split: val
      shuffle: false
      tokenizer_name: ${tokenizer_name}
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
    drop_last: false
    num_workers: 8

  # Optimization
  scheduler:
    name: cosine_with_warmup
    t_warmup: 0.1dur
    alpha_f: 0.01

  optimizer:
    name: decoupled_lionw
    lr: 3.2e-4
    betas:
      - 0.9
      - 0.95
    weight_decay: 3.2e-5

  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  max_duration: 12400ba # ~ 26B tokens
  eval_interval: 500ba
  eval_subset_num_batches: -1
  eval_first: true
  global_train_batch_size: 1024 # ~ 2M tokens

  # System
  seed: ${global_seed}
  device_eval_batch_size: 4
  device_train_microbatch_size: 4
  precision: amp_bf16

  # FSDP
  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: PURE
    activation_checkpointing: false
    activation_cpu_offload: false
    verbose: true

  # Logging
  progress_bar: false
  log_to_console: true
  console_log_interval: 50ba

  callbacks:
    speed_monitor:
      window_size: 10
    runtime_estimator: {}
    lr_monitor: {}
    memory_monitor: {}
    optimizer_monitor: {}
    health_checker:
      test_mode: true

  loggers:
    wandb: {}

  save_interval: 500ba
  save_folder: *save_folder
  save_num_checkpoints_to_keep: 1
  autoresume: true